export default defineAppConfig({
	pages: [
		'pages/home/index',
		'pages/activity/index',
		'pages/activity/detail/index',
		'pages/activity/check/index',
		'pages/demand/index',
		'pages/demand/detail/index',
		'pages/demand/publish/index',
		'pages/demand/bid/index',
		'pages/job/index',
		'pages/job/detail/index',
		'pages/job/enterprise/index',
		'pages/user/index',
		'pages/user/profile/index',
		'pages/user/activity/index',
		'pages/user/demand/index',
		'pages/user/demand/edit/index',
		'pages/user/demand/bid/index',
		'pages/user/bid/index',
		'pages/user/bid/edit/index',
		'pages/user/resume/index',
		'pages/user/job/index',
		'pages/provider/index',
		'pages/apply/index',
		'pages/apply/history/index',
		'pages/apply/volunteer/index',
		'pages/apply/institution/index',
		'pages/order/provider/index',
		'pages/order/employer/index',
		'pages/order/detail/index',
		'pages/order/comment/index',
		'pages/onboarding/index',
		'pages/login/index',
	],
	window: {
		backgroundTextStyle: 'light',
		navigationBarBackgroundColor: '#fff',
		navigationBarTitleText: 'WeChat',
		navigationBarTextStyle: 'black',
	},
	tabBar: {
		list: [
			{
				iconPath: 'assets/tabbar/home.png',
				selectedIconPath: 'assets/tabbar/home_fill.png',
				pagePath: 'pages/home/index',
				text: '首页',
			},
			{
				iconPath: 'assets/tabbar/activity.png',
				selectedIconPath: 'assets/tabbar/activity_fill.png',
				pagePath: 'pages/activity/index',
				text: '志愿活动',
			},
			{
				iconPath: 'assets/tabbar/demand.png',
				selectedIconPath: 'assets/tabbar/demand_fill.png',
				pagePath: 'pages/demand/index',
				text: '服务大厅',
			},
			{
				iconPath: 'assets/tabbar/job.png',
				selectedIconPath: 'assets/tabbar/job_fill.png',
				pagePath: 'pages/job/index',
				text: '求职',
			},
			{
				iconPath: 'assets/tabbar/user.png',
				selectedIconPath: 'assets/tabbar/user_fill.png',
				pagePath: 'pages/user/index',
				text: '我的',
			},
		],
		color: '#3a3a3a',
		selectedColor: '#EA3323',
		backgroundColor: '#fff',
		borderStyle: 'white',
	},
	permission: {
		'scope.userLocation': {
			desc: '您的位置信息将用于核验您是否已到达志愿活动履约现场',
		},
	},
});
